//
//  ListOfCourses.swift
//  RasmussenTechnology
//
//  Created by Hector Torres.
//  Copyright © 2017 Hector Torres. All rights reserved.
//

import UIKit

//Major and Core Courses
let cda1330c = Course(courseID: "CDA 1330C", courseName: "Operating Systems", courseCredits: 4)
let cet2660c = Course(courseID: "CET 2660C", courseName: "Networking Security", courseCredits: 3)
let cis1538c = Course(courseID: "CIS 1538C", courseName: "Hardware and Software I", courseCredits: 4)
let cis1648c = Course(courseID: "CIS 1648C", courseName: "Hardware and Software II", courseCredits: 4)
let cis1710c = Course(courseID: "CIS 1710C", courseName: "Administering Windows Server", courseCredits: 4)
let cis2911 = Course(courseID: "CIS 2911", courseName: "Information Technology Capstone", courseCredits: 2)
let cnt1244c = Course(courseID: "CNT 1244C", courseName: "Introduction to Networks", courseCredits: 3)
let cts1884c = Course(courseID: "CTS 1884C", courseName: "Cimputer Technical Support", courseCredits: 3)
let cts2511 = Course(courseID: "CTS 2511", courseName: "Excel", courseCredits: 3)
let geb1011 = Course(courseID: "GEB 1011", courseName: "Introduction to Business", courseCredits: 4)
let ism2541c = Course(courseID: "ISM 2541C", courseName: "Project Management and Team Leadership", courseCredits: 3)
let man2021 = Course(courseID: "MAN 2021", courseName: "Principles of Management", courseCredits: 4)
let cda2725c = Course(courseID: "CDA 2725C", courseName: "Systems Analysis and Design", courseCredits: 3)
let cda3515c = Course(courseID: "CDA 3515C", courseName: "Information Technology Systems Analysis", courseCredits: 4)
let cda3626c = Course(courseID: "CDA 3626C", courseName: "Information Technology Systems Design", courseCredits: 4)
let cis3550c = Course(courseID: "CIS 3550C", courseName: "Information Technology Business Administration", courseCredits: 4)
let cis3574c = Course(courseID: "CIS 3574C", courseName: "Organizational Policy", courseCredits: 3)
let cis4005c = Course(courseID: "CIS 4005C", courseName: "IT Operations Management", courseCredits: 4)
let cis4189c = Course(courseID: "CIS 4189C", courseName: "Risk Management and Business Continuity", courseCredits: 4)
let cis4412c = Course(courseID: "CIS 4412C", courseName: "Information Technology Security", courseCredits: 4)
let cis4929c = Course(courseID: "CIS 4929C", courseName: "IT Management Capstone", courseCredits: 4)
let cnt3229 = Course(courseID: "CNT 3229", courseName: "Asset Management", courseCredits: 3)
let cnt3348 = Course(courseID: "CNT 3348", courseName: "Infrastructure and Hardware", courseCredits: 4)
let cnt4283 = Course(courseID: "CNT 4283", courseName: "Enterprise Application Support", courseCredits: 4)
let cnt4437 = Course(courseID: "CNT 4437", courseName: "Service Management", courseCredits: 4)
let ism3015 = Course(courseID: "ISM 3015", courseName: "Management of Information Systems", courseCredits: 4)
let ism3110c = Course(courseID: "ISM 3110C", courseName: "Information Technology Project Management Tools", courseCredits: 4)
let ism3255c = Course(courseID: "ISM 3255C", courseName: "Information Technology Project Management I", courseCredits: 4)
let ism4470c = Course(courseID: "ISM 4470C", courseName: "Information Technology Project Management II", courseCredits: 4)
let ism4505c = Course(courseID: "ISM 4505C", courseName: "Information Technology Organization Support", courseCredits: 4)
let cet2522c = Course(courseID: "CET 2522C", courseName: "Cisco Network Routing and Switching", courseCredits: 3)
let cis1308 = Course(courseID: "CIS 1308", courseName: "Logic and Troubleshooting", courseCredits: 4)
let cis2647c = Course(courseID: "CIS 2647C", courseName: "Windows Directory Server", courseCredits: 4)
let cis2960c = Course(courseID: "CIS2960C", courseName: "Network Systems Administration Capston", courseCredits: 2)
let cts2321 = Course(courseID: "CTS 2321", courseName: "Linux Administration", courseCredits: 3)
let ism2321 = Course(courseID: "ISM 2321", courseName: "Managing Information Security", courseCredits: 3)
let cis3140c = Course(courseID: "CIS 3140C", courseName: "Advanced Cisco Network Security-CCNA", courseCredits: 4)
let cis3209c = Course(courseID: "CIS 3209C", courseName: "SSCP Certification Preparation", courseCredits: 4)
let cis3257 = Course(courseID: "CIS 3257", courseName: "Legal and Security Issues", courseCredits: 4)
let cis3375c = Course(courseID: "CIS 3375C", courseName: "Wireless, Mobile, and Cloud Security", courseCredits: 3)
let cis3664 = Course(courseID: "CIS 3664", courseName: "Security Strategies for Web APPs and Social Networking", courseCredits: 3)
let cis4039 = Course(courseID: "CIS 4039", courseName: "Auditing Informaiton Technology Infrastructure", courseCredits: 4)
let cis4137 = Course(courseID: "CIS 4137", courseName: "Access Controles, Authentication, and PKI", courseCredits: 4)
let cis4215 = Course(courseID: "CIS 4215", courseName: "Windows Security Strategies", courseCredits: 4)
let cis4352 = Course(courseID: "CIS 4352", courseName: "Linux Security Strategies", courseCredits: 4)
let cis4362c = Course(courseID: "CIS 4362C", courseName: "Network Security and Cryptography", courseCredits: 3)
let cis4385c = Course(courseID: "CIS 4385C", courseName: "Computer Forensics", courseCredits: 3)
let cis4456 = Course(courseID: "CIS 4456", courseName: "Hacker Techniques, Tools, and Applicaitons", courseCredits: 4)
let cis4581 = Course(courseID: "CIS 4581", courseName: "ISS Capstone", courseCredits: 3)
let cnt3126 = Course(courseID: "CNT 3126", courseName: "Advanced Networking", courseCredits: 4)
let cnt3777 = Course(courseID: "CNT 3777", courseName: "Virtualization", courseCredits: 4)
let cnt3849c = Course(courseID: "CNT 3849C", courseName: "Scripting-Shell Scripting/Python/Perl", courseCredits: 4)
let cnt4016 = Course(courseID: "CNT 4016", courseName: "Cloud Computing", courseCredits: 4)
let cda1028c = Course(courseID: "CDA 1028C", courseName: "Introduction to Software Architecture", courseCredits: 3)
let cda1202 = Course(courseID: "CDA 1202", courseName: "Foundations of Software Design", courseCredits: 3)
let cis2983c = Course(courseID: "CIS 2983C", courseName: "Software Application Developnebt Capstone", courseCredits: 2)
let cop1044c = Course(courseID: "COP 1044C", courseName: "Introduction to Object-Oriented Programming", courseCredits: 3)
let cop1350c = Course(courseID: "COP 1350C", courseName: "C++ Programming", courseCredits: 4)
let cop1532c = Course(courseID: "COP 1532C", courseName: "Database Fundamentals for Programmers", courseCredits: 3)
let cop2268c = Course(courseID: "COP 2268C", courseName: "Java Programming", courseCredits: 3)
let cop2350c = Course(courseID: "COP 2350C", courseName: "Advanced C++ Programming", courseCredits: 4)
let cop2456c = Course(courseID: "COP 2456C", courseName: "Microsoft C# Programming", courseCredits: 3)
let cop2570c = Course(courseID: "COP 2570C", courseName: "Programming Data Structures", courseCredits: 4)
let cop2598c = Course(courseID: "COP 2598C", courseName: "Secure Programming Techniques", courseCredits: 4)
let cop2664c = Course(courseID: "COP 2664C", courseName: "Advanced Database Programming Techniques", courseCredits: 3)
let e242 = Course(courseID: "E242", courseName: "Career Development", courseCredits: 2)
let cda2520c = Course(courseID: "CDA 2520C", courseName: "Web Frameworks", courseCredits: 3)
let cen1400 = Course(courseID: "CEN 1400", courseName: "Mobile Application Development", courseCredits: 3)
let cgs1820c = Course(courseID: "CGS 1820C", courseName: "Introduction to HTML", courseCredits: 3)
let cop1801 = Course(courseID: "COP 1801", courseName: "JavaScript", courseCredits: 3)
let cop2810c = Course(courseID: "COP 2810C", courseName: "Database Driven Programming", courseCredits: 3)
let cop2890 = Course(courseID: "COP 2890", courseName: "Web Programming Capstone", courseCredits: 2)
let cda3315c = Course(courseID: "CDA 3315C", courseName: "Fundamentals of Enterprise Architecture", courseCredits: 4)
let cda3428c = Course(courseID: "CDA 3428C", courseName: "Fundamentals of Distributed Application Architecture", courseCredits: 4)
let cis3801c = Course(courseID: "CDA 3801C", courseName: "Fundamentals of Mobile Wev Application Development", courseCredits: 4)
let cis3917c = Course(courseID: "CDA 3917C", courseName: "Fundamentals of Distributed Database Management", courseCredits: 4)
let cis4655c = Course(courseID: "CIS 4655C", courseName: "Advanced Mobile Web Application Development", courseCredits: 4)
let cis4793c = Course(courseID: "CIS 4793C", courseName: "Database Implementation Strategies for Programmers", courseCredits: 4)
let cis4836c = Course(courseID: "CIS 4836C", courseName: "Web Analytics", courseCredits: 4)
let cis4910c = Course(courseID: "CIS 4910C", courseName: "Computer Science Capstone", courseCredits: 3)
let cts3265c = Course(courseID: "CTS 3265C", courseName: "Introduction to Business Intelligence", courseCredits: 4)
let cts3302c = Course(courseID: "CTS 3302C", courseName: "Fundamentals of Cloud Computing", courseCredits: 4)
let cts4557 = Course(courseID: "CTS 4557", courseName: "Emerging Trends in Technology", courseCredits: 3)
let cts4623c = Course(courseID: "CTS 4623C", courseName: "Advanced Cloud Computing Technologies", courseCredits: 4)
let geb3422 = Course(courseID: "GEB 3422", courseName: "Business Project Management", courseCredits: 4)
let man3504 = Course(courseID: "MAN 3504", courseName: "Operations Management", courseCredits: 4)
let cop3362c = Course(courseID: "COP 3362C", courseName: "Apple iOS Programming I", courseCredits: 4)
let cop4309c = Course(courseID: "COP 4309C", courseName: "Apple iOS Programming II", courseCredits: 4)
let cop4683c = Course(courseID: "COP 4683C", courseName: "Apple iOS Cloud Integration", courseCredits: 4)
let cop3488c = Course(courseID: "COP 3488C", courseName: "Universal Windows Applications Programming I", courseCredits: 4)
let cop4474c = Course(courseID: "COP 4474C", courseName: "Universal Windows Applications Programming II", courseCredits: 4)
let cop4777c = Course(courseID: "COP 4777C", courseName: "Universal Windows Applications Cloud Integration", courseCredits: 4)
let idc3152 = Course(courseID: "IDC 3152", courseName: "Enterprise Resource Reporting", courseCredits: 4)
let qmb3000 = Course(courseID: "QMB 3000", courseName: "Introduction to Data Analytics", courseCredits: 4)
let qmb3100 = Course(courseID: "QMB 3100", courseName: "Foundations of Analytics PLatforms, Environments, and Software", courseCredits: 4)
let qmb3200 = Course(courseID: "QMB 3200", courseName: "Introduction to Scripting", courseCredits: 4)
let qmb3300 = Course(courseID: "QMB 3300", courseName: "Introduction to Data Visualization", courseCredits: 4)
let qmb4000 = Course(courseID: "QMB 4000", courseName: "Data Elements", courseCredits: 4)
let qmb4100 = Course(courseID: "QMB 4100", courseName: "Applied Business Intelligence", courseCredits: 4)
let qmb4200 = Course(courseID: "QMB 4200", courseName: "Advanced Analytics Platforms, Environments, and Software", courseCredits: 4)
let qmb4300 = Course(courseID: "QMB 4300", courseName: "Data Quality in Analyitcs", courseCredits: 4)
let qmb4400 = Course(courseID: "QMB 4400", courseName: "Data Analysis and Optimization", courseCredits: 4)
let qmb4500 = Course(courseID: "QMB 4500", courseName: "Data Visualization Implementation and Communication", courseCredits: 4)
let qmb4900 = Course(courseID: "QMB 4900", courseName: "Data Analytics Capstone", courseCredits: 3)