//
//  ListOfCourses.swift
//  RasmussenTechnology
//
//  Created by Hector Torres.
//  Copyright © 2017 Hector Torres. All rights reserved.
//

import UIKit

let cda1330c = Course(courseID: "CDA 1330C", courseName: "Operating Systems", courseCredits: 4)
let cet2660c = Course(courseID: "CET 2660C", courseName: "Networking Security", courseCredits: 3)
let cis1538c = Course(courseID: "CIS 1538C", courseName: "Hardware and Software I", courseCredits: 4)
let cis1648c = Course(courseID: "CIS 1648C", courseName: "Hardware and Software II", courseCredits: 4)
let cis1710c = Course(courseID: "CIS 1710C", courseName: "Administering Windows Server", courseCredits: 4)
let cis2911 = Course(courseID: "CIS 2911", courseName: "Information Technology Capstone", courseCredits: 2)
let cnt1244c = Course(courseID: "CNT 1244C", courseName: "Introduction to Networks", courseCredits: 3)
let cts1884c = Course(courseID: "CTS 1884C", courseName: "Cimputer Technical Support", courseCredits: 3)
let cts2511 = Course(courseID: "CTS 2511", courseName: "Excel", courseCredits: 3)
let geb1011 = Course(courseID: "GEB 1011", courseName: "Introduction to Business", courseCredits: 4)
let ism2541c = Course(courseID: "ISM 2541C", courseName: "Project Management and Team Leadership", courseCredits: 3)
let man2021 = Course(courseID: "MAN 2021", courseName: "Principles of Management", courseCredits: 4)
let cda2725c = Course(courseID: "CDA 2725C", courseName: "Systems Analysis and Design", courseCredits: 3)
let cda3515c = Course(courseID: "CDA 3515C", courseName: "Information Technology Systems Analysis", courseCredits: 4)
let cda3626c = Course(courseID: "CDA 3626C", courseName: "Information Technology Systems Design", courseCredits: 4)
let cis3550c = Course(courseID: "CIS 3550C", courseName: "Information Technology Business Administration", courseCredits: 4)
let cis3574c = Course(courseID: "CIS 3574C", courseName: "Organizational Policy", courseCredits: 3)
let cis4005c = Course(courseID: "CIS 4005C", courseName: "IT Operations Management", courseCredits: 4)
let cis4189c = Course(courseID: "CIS 4189C", courseName: "Risk Management and Business Continuity", courseCredits: 4)
let cis4412c = Course(courseID: "CIS 4412C", courseName: "Information Technology Security", courseCredits: 4)
let cis4929c = Course(courseID: "CIS 4929C", courseName: "IT Management Capstone", courseCredits: 4)
let cnt3229 = Course(courseID: "CNT 3229", courseName: "Asset Management", courseCredits: 3)
let cnt3348 = Course(courseID: "CNT 3348", courseName: "Infrastructure and Hardware", courseCredits: 4)
let cnt4283 = Course(courseID: "CNT 4283", courseName: "Enterprise Application Support", courseCredits: 4)
let cnt4437 = Course(courseID: "CNT 4437", courseName: "Service Management", courseCredits: 4)
let ism3015 = Course(courseID: "ISM 3015", courseName: "Management of Information Systems", courseCredits: 4)
let ism3110c = Course(courseID: "ISM 3110C", courseName: "Information Technology Project Management Tools", courseCredits: 4)
let ism3255c = Course(courseID: "ISM 3255C", courseName: "Information Technology Project Management I", courseCredits: 4)
let ism4470c = Course(courseID: "ISM 4470C", courseName: "Information Technology Project Management II", courseCredits: 4)
let ism4505c = Course(courseID: "ISM 4505C", courseName: "Information Technology Organization Support", courseCredits: 4)
let cet2522c = Course(courseID: "CET 2522C", courseName: "Cisco Network Routing and Switching", courseCredits: 3)
let cis1308 = Course(courseID: "CIS 1308", courseName: "Logic and Troubleshooting", courseCredits: 4)
let cis2647c = Course(courseID: "CIS 2647C", courseName: "Windows Directory Server", courseCredits: 4)
let cis2960c = Course(courseID: "CIS2960C", courseName: "Network Systems Administration Capston", courseCredits: 2)
let cts2321 = Course(courseID: "CTS 2321", courseName: "Linux Administration", courseCredits: 3)
let ism2321 = Course(courseID: "ISM 2321", courseName: "Managing Information Security", courseCredits: 3)
let cis3140c = Course(courseID: "CIS 3140C", courseName: "Advanced Cisco Network Security-CCNA", courseCredits: 4)
let cis3209 = Course(courseID: "CIS 3209C", courseName: "SSCP Certification Preparation", courseCredits: 4)
let cis3257 = Course(courseID: "CIS 3257", courseName: "Legal and Security Issues", courseCredits: 4)
let cis3375c = Course(courseID: "CIS 3375C", courseName: "Wireless, Mobile, and Cloud Security", courseCredits: 3)
let cis3664 = Course(courseID: "CIS 3664", courseName: "Security Strategies for Web APPs and Social Networking", courseCredits: 3)
let cis4039 = Course(courseID: "CIS 4039", courseName: "Auditing Informaiton Technology Infrastructure", courseCredits: 4)
let cis4137 = Course(courseID: "CIS 4137", courseName: "Access Controles, Authentication, and PKI", courseCredits: 4)
let cis4215 = Course(courseID: "CIS 4215", courseName: "Windows Security Strategies", courseCredits: 4)
let cis4352 = Course(courseID: "CIS 4352", courseName: "Linux Security Strategies", courseCredits: 4)
let cis4362c = Course(courseID: "CIS 4362C", courseName: "Network Security and Cryptography", courseCredits: 3)
let cis4385c = Course(courseID: "CIS 4385C", courseName: "Computer Forensics", courseCredits: 3)
let cis4456 = Course(courseID: "CIS 4456", courseName: "Hacker Techniques, Tools, and Applicaitons", courseCredits: 4)
let cis4581 = Course(courseID: "CIS 4581", courseName: "ISS Capstone", courseCredits: 3)
let cnt3126 = Course(courseID: "CNT 3126", courseName: "Advanced Networking", courseCredits: 4)
let cnt3777 = Course(courseID: "CNT 3777", courseName: "Virtualization", courseCredits: 4)
let cnt3849c = Course(courseID: "CNT 3849C", courseName: "Scripting-Shell Scripting/Python/Perl", courseCredits: 4)
let cnt4016 = Course(courseID: "CNT 4016", courseName: "Cloud Computing", courseCredits: 4)
let cda1028c = Course(courseID: "CDA 1028C", courseName: "Introduction to Software Architecture", courseCredits: 3)
let cda1202 = Course(courseID: "CDA 1202", courseName: "Foundations of Software Design", courseCredits: 3)
let cis2983c = Course(courseID: "CIS 2983C", courseName: "Software Application Developnebt Capstone", courseCredits: 2)
let cop1044c = Course(courseID: "COP 1044C", courseName: "Introduction to Object-Oriented Programming", courseCredits: 3)

